// The bundled sample meet is a shipped feature (Home → "Load sample meet"),
// and it is cast to MeetState on import, so nothing else would catch it going
// stale if the state shape changes. These assertions run the real domain
// engine over it and pin the results.
//
// The meet itself is generated by `npm run build-sample`, which drives the same
// engine — so if one of these fails after a rebuild, the meet changed, not the
// rules. Read the numbers below as a description of what the demo shows.

import { describe, expect, it } from 'vitest';
import sample from '../sample-meet.json';
import { computeDivisionResults } from '../../domain/championship';
import type { Entry, MeetState } from '../../domain/types';

const state = sample as unknown as MeetState;
const entryMap = new Map<string, Entry>(state.entries.map((e) => [e.id, e]));

const resultsFor = (name: string) => {
  const div = state.divisions.find((d) => d.name === name)!;
  const res = computeDivisionResults(div, state.draws, entryMap);
  return res.standings.map((s) => ({
    name: entryMap.get(s.entryId)!.callName,
    total: s.total,
    ...res.awards[s.entryId],
  }));
};

describe('bundled sample meet', () => {
  it('is a complete, finished meet that opens on the home page', () => {
    expect(state.phase).toBe('home');
    expect(state.info.meetId).toBe('2026-A02');
    expect(state.entries).toHaveLength(28);
    expect(state.divisions).toHaveLength(4);
    expect([...new Set(state.draws.map((d) => d.program))].sort()).toEqual([1, 2, 3]);
    expect(state.draws.every((d) => d.races.every((r) => r.finished))).toBe(true);
  });

  it('covers the outcome types a secretary needs to see demonstrated', () => {
    const kinds = new Set(
      state.draws.flatMap((d) => d.races.flatMap((r) => Object.values(r.outcomes).map((o) => o.kind)))
    );
    for (const kind of ['placed', 'ABS', 'DNF', 'OC', 'DQ']) expect(kinds).toContain(kind);
    expect(state.entries.some((e) => e.preScratched)).toBe(true);
  });

  it('shows the breeds that actually turn out, sighthound and not', () => {
    const breeds = new Set(state.entries.map((e) => e.breed));
    for (const breed of ['WHIPPET', 'BORDER COLLIE', 'TAIGAN', 'SALUKI', 'AZAWAKH']) {
      expect(breeds).toContain(breed);
    }
    const mixed = state.divisions.find((d) => d.type === 'mixed')!;
    const inMixed = new Set(mixed.entryIds.map((id) => entryMap.get(id)!.breed));
    expect(inMixed).toContain('AZAWAKH');
    expect(inMixed).toContain('SALUKI');
  });

  it('runs a nine-dog division on Figure 8.1\'s odd row', () => {
    const whippets = state.divisions.find((d) => d.name === 'WHIPPET')!;
    const p1 = state.draws.find((d) => d.divisionId === whippets.id && d.program === 1)!;
    // 9 dogs is 3 / 2 / 4 in run order, not an even split (chart.ts).
    expect(p1.races.map((r) => r.slots.length)).toEqual([3, 2, 4]);
    expect(p1.races[2].isHP).toBe(true);
  });

  it('scores every division without error', () => {
    for (const div of state.divisions) {
      expect(() => computeDivisionResults(div, state.draws, entryMap)).not.toThrow();
    }
  });

  it('splits championship points between dogs tied on race points (5.2)', () => {
    const whippets = resultsFor('WHIPPET');
    // Axl and Baker both finish on 12, in the 3rd and 4th high-score slots of
    // an eligible entry of 8 -> they share (0.5 + 0) / 2 = 0.25 each.
    expect(whippets.filter((r) => r.name === 'Axl' || r.name === 'Baker')).toEqual([
      expect.objectContaining({ name: 'Axl', total: 12, brc: 0.25 }),
      expect.objectContaining({ name: 'Baker', total: 12, brc: 0.25 }),
    ]);
  });

  it('pays a leftover dog mixed points only (4.1.7 / 5.3 / 5.4)', () => {
    const whippets = state.divisions.find((d) => d.name === 'WHIPPET')!;
    const sloughi = state.entries.find((e) => e.breed === 'SLOUGHI')!;
    expect(whippets.leftoverIds).toContain(sloughi.id);

    const row = resultsFor('WHIPPET').find((r) => r.name === sloughi.callName)!;
    expect(row).toEqual(
      expect.objectContaining({
        mrc: 0.5, // third overall, so the 3rd high-score mixed slot
        brc: 0, //  a leftover takes no breed points
        nbrc: 0, // and is not a starter for National Breed either
      })
    );
  });

  it('withholds breed points from a titled champion but not national points', () => {
    // Atari holds a BRC. Finishing behind a non-titled dog he does not reduce
    // the eligible entry, earns no BRC, and still takes National Breed points.
    const atari = resultsFor('BORDER COLLIE').find((r) => r.name === 'Atari')!;
    expect(atari.brc).toBe(0);
    expect(atari.nbrc).toBeGreaterThan(0);
    expect(entryMap.get(state.entries.find((e) => e.callName === 'Atari')!.id)!.hasBRC).toBe(true);
  });

  it('gives Turtle Racing points to the one dog that earned them (5.7)', () => {
    const trcWinners = state.divisions
      .flatMap((d) => resultsFor(d.name))
      .filter((r) => r.trc > 0)
      .map((r) => r.name);
    // Last place in its division having finished every race. The other three
    // divisions end on a dog that did not complete the meet, which bars it.
    expect(trcWinners).toEqual(['Ak-Tosh']);
  });
});
