// The bundled sample meet is a shipped feature (Home → "Load sample meet"),
// and it is cast to MeetState on import, so nothing else would catch it going
// stale if the state shape changes. These assertions run the real domain
// engine over it and pin the results.
//
// The meet itself is generated by `npm run build-sample`, which drives the same
// engine — so if one of these fails after a rebuild, the meet changed, not the
// rules. Read the numbers below as a description of what the demo shows.

import { describe, expect, it } from 'vitest';
import sample from '../sample-meet.json';
import { computeDivisionResults } from '../../domain/championship';
import type { Entry, MeetState } from '../../domain/types';

const state = sample as unknown as MeetState;
const entryMap = new Map<string, Entry>(state.entries.map((e) => [e.id, e]));

const divisionNamed = (name: string) => state.divisions.find((d) => d.name === name)!;
const resultsOf = (name: string) => computeDivisionResults(divisionNamed(name), state.draws, entryMap);

const standingsOf = (name: string) => {
  const res = resultsOf(name);
  return res.standings.map((s) => ({
    name: entryMap.get(s.entryId)!.callName,
    place: s.place,
    total: s.total,
    ...res.awards[s.entryId],
  }));
};

const row = (division: string, dog: string) => standingsOf(division).find((r) => r.name === dog)!;

describe('bundled sample meet', () => {
  it('is a complete, finished meet that opens on the home page', () => {
    expect(state.phase).toBe('home');
    expect(state.info.meetId).toBe('2026-A02');
    expect(state.entries).toHaveLength(29);
    expect(state.divisions).toHaveLength(6);
    expect([...new Set(state.draws.map((d) => d.program))].sort()).toEqual([1, 2, 3]);
    expect(state.draws.every((d) => d.races.every((r) => r.finished))).toBe(true);
  });

  it('covers the outcome types a secretary needs to see demonstrated', () => {
    const kinds = new Set(
      state.draws.flatMap((d) => d.races.flatMap((r) => Object.values(r.outcomes).map((o) => o.kind)))
    );
    for (const kind of ['placed', 'ABS', 'DNF', 'OC', 'DQ']) expect(kinds).toContain(kind);
    expect(state.entries.some((e) => e.preScratched)).toBe(true);
  });

  it('gives each sighthound breed its own division and pools the rest', () => {
    expect(state.divisions.filter((d) => d.type === 'breed').map((d) => d.name).sort()).toEqual([
      'AZAWAKH',
      'BORDER COLLIE',
      'SALUKI',
      'TAIGAN',
      'WHIPPET',
    ]);
    // The herding breeds run mixed: two Belgian Shepherds, and the only Dutch
    // Shepherd in the guide, who has nobody of her own to run against.
    const mixed = divisionNamed('MIXED');
    expect(mixed.type).toBe('mixed');
    expect(mixed.entryIds.map((id) => entryMap.get(id)!.breed).sort()).toEqual([
      'BELGIAN SHEPHERD DOG',
      'BELGIAN SHEPHERD DOG',
      'DUTCH SHEPHERD',
    ]);
  });

  it("runs a nine-dog division on Figure 8.1's odd row", () => {
    const p1 = state.draws.find((d) => d.divisionId === divisionNamed('WHIPPET').id && d.program === 1)!;
    // 9 dogs is 3 / 2 / 4 in run order, not an even split (chart.ts).
    expect(p1.races.map((r) => r.slots.length)).toEqual([3, 2, 4]);
    expect(p1.races[2].isHP).toBe(true);
  });

  it('scores every division without error', () => {
    for (const div of state.divisions) {
      expect(() => computeDivisionResults(div, state.draws, entryMap)).not.toThrow();
    }
  });

  it('places a leftover with dogs it can fairly race and pays it mixed points only', () => {
    // A Sloughi entering alone has no division of his own (4.1.7). He is put
    // with the Azawakhs — comparable size and running style — not the Whippets.
    const sloughi = state.entries.find((e) => e.breed === 'SLOUGHI')!;
    expect(divisionNamed('AZAWAKH').leftoverIds).toContain(sloughi.id);
    expect(divisionNamed('WHIPPET').leftoverIds).toEqual([]);

    expect(row('AZAWAKH', sloughi.callName)).toEqual(
      expect.objectContaining({ place: 2, mrc: 0.5, brc: 0, nbrc: 0 })
    );
    // A leftover consumes no breed slot, so the Azawakh behind him still takes
    // the second breed award rather than the third.
    expect(row('AZAWAKH', 'Amidi')).toEqual(expect.objectContaining({ place: 3, brc: 0.5 }));
  });

  it('splits championship points between dogs tied on race points (5.2)', () => {
    // Bandit-S and Baker both finish on 15 in the 2nd and 3rd high-score slots
    // of an eligible entry of 9, so they share (1.5 + 0.5) / 2 = 1.0 each.
    expect(row('WHIPPET', 'Bandit-S')).toEqual(expect.objectContaining({ total: 15, brc: 1 }));
    expect(row('WHIPPET', 'Baker')).toEqual(expect.objectContaining({ total: 15, brc: 1 }));
    // And again a division over, on a smaller chart row: 0.5 each.
    expect(row('BORDER COLLIE', 'Critter')).toEqual(expect.objectContaining({ total: 12, brc: 0.5 }));
    expect(row('BORDER COLLIE', 'Akira')).toEqual(expect.objectContaining({ total: 12, brc: 0.5 }));
  });

  it('subtracts a champion who wins from the eligible entry (5.2)', () => {
    // Atari holds a BRC and wins the division outright. Placing above the first
    // non-titled dog he comes off the eligible entry: 6 starters, entry of 5.
    // He earns no breed points and still takes National Breed points, and
    // Dillon behind him is the High Score Dog for breed purposes.
    expect(entryMap.get(state.entries.find((e) => e.callName === 'Atari')!.id)!.hasBRC).toBe(true);
    expect(resultsOf('BORDER COLLIE').eligibleEntryBreed).toBe(5);
    expect(row('BORDER COLLIE', 'Atari')).toEqual(
      expect.objectContaining({ place: 1, brc: 0, nbrc: 2 })
    );
    expect(row('BORDER COLLIE', 'Dillon')).toEqual(expect.objectContaining({ place: 2, brc: 2 }));
  });

  it('gives Turtle Racing points only to a last dog that finished (5.7)', () => {
    const trcWinners = state.divisions
      .flatMap((d) => standingsOf(d.name))
      .filter((r) => r.trc > 0)
      .map((r) => r.name)
      .sort();
    expect(trcWinners).toEqual(['Ak-Tosh', 'Annie', 'Birdie']);

    // Dori finishes last in mixed but did not finish every race, which bars her.
    expect(standingsOf('MIXED').at(-1)!.name).toBe('Dori');
    expect(row('MIXED', 'Dori').trc).toBe(0);
  });
});
