// The two bundled sample meets are a shipped feature (Home → "Try it out"),
// and both are cast to MeetState on import, so nothing else would catch one
// going stale if the state shape changes. These assertions run the real domain
// engine over them and pin the results.
//
// Meet 1 is a capture from the real UI and is frozen — leave it alone. Meet 2
// is generated by `npm run build-sample`, which drives the same engine, so if
// one of its assertions fails after a rebuild then the meet changed, not the
// rules. Read those numbers as a description of what it shows.

import { describe, expect, it } from 'vitest';
import meet1 from '../sample-meet-1.json';
import meet2 from '../sample-meet-2.json';
import { computeDivisionResults } from '../../domain/championship';
import type { Entry, MeetState } from '../../domain/types';

const smallMeet = meet1 as unknown as MeetState;
const largeMeet = meet2 as unknown as MeetState;

const mapOf = (state: MeetState) => new Map<string, Entry>(state.entries.map((e) => [e.id, e]));

const divisionNamed = (state: MeetState, name: string) =>
  state.divisions.find((d) => d.name === name)!;

const resultsOf = (state: MeetState, name: string) =>
  computeDivisionResults(divisionNamed(state, name), state.draws, mapOf(state));

const standingsOf = (state: MeetState, name: string) => {
  const entryMap = mapOf(state);
  const res = resultsOf(state, name);
  return res.standings.map((s) => ({
    name: entryMap.get(s.entryId)!.callName,
    place: s.place,
    total: s.total,
    ...res.awards[s.entryId],
  }));
};

const row = (state: MeetState, division: string, dog: string) =>
  standingsOf(state, division).find((r) => r.name === dog)!;

const dogNamed = (state: MeetState, callName: string) =>
  state.entries.find((e) => e.callName === callName)!;

// ---------------------------------------------------------------- both meets

const SAMPLES = [
  { label: '1', state: smallMeet, meetId: '2026-A01', entries: 19, divisions: 4 },
  { label: '2', state: largeMeet, meetId: '2026-A02', entries: 29, divisions: 6 },
];

describe.each(SAMPLES)('example meet $label', ({ state, meetId, entries, divisions }) => {
  it('is a complete, finished meet that opens on the home page', () => {
    expect(state.phase).toBe('home');
    expect(state.info.meetId).toBe(meetId);
    expect(state.entries).toHaveLength(entries);
    expect(state.divisions).toHaveLength(divisions);
    expect([...new Set(state.draws.map((d) => d.program))].sort()).toEqual([1, 2, 3]);
    expect(state.draws.every((d) => d.races.every((r) => r.finished))).toBe(true);
  });

  it('covers the outcome types a secretary needs to see demonstrated', () => {
    const kinds = new Set(
      state.draws.flatMap((d) => d.races.flatMap((r) => Object.values(r.outcomes).map((o) => o.kind)))
    );
    for (const kind of ['placed', 'ABS', 'DNF', 'OC', 'DQ']) expect(kinds).toContain(kind);
    expect(state.entries.some((e) => e.preScratched)).toBe(true);
  });

  it('scores every division without error', () => {
    for (const div of state.divisions) {
      expect(() => computeDivisionResults(div, state.draws, mapOf(state))).not.toThrow();
    }
  });
});

// -------------------------------------------------------------- meet 1: A01

describe('example meet 1 (2026-A01)', () => {
  it('splits championship points between dogs tied on race points (5.2)', () => {
    const jrt = standingsOf(smallMeet, 'JACK RUSSELL TERRIER');
    // 7 starters -> chart row [2.0, 1.0]; Coco Puff and Arthur both finish on
    // 17 points, so they share the 1st+2nd values: (2.0 + 1.0) / 2 = 1.5 each.
    expect(jrt.slice(0, 2)).toEqual([
      expect.objectContaining({ name: 'Coco Puff', total: 17, brc: 1.5 }),
      expect.objectContaining({ name: 'Arthur', total: 17, brc: 1.5 }),
    ]);
  });

  it('awards an MRC champion breed points but withholds TRC from unfinished dogs', () => {
    // Azhidar holds an MRC title, which does not bar him from BRC points.
    const taigan = standingsOf(smallMeet, 'TAIGAN');
    expect(taigan[0]).toEqual(expect.objectContaining({ name: 'Ak-Tosh', brc: 1 }));
    expect(taigan[1]).toEqual(expect.objectContaining({ name: 'Azhidar', brc: 0.5 }));

    // The only last-place dog that finished every race is Birdie, so she is the
    // only Turtle Racing point earner in the meet (5.7).
    const trcWinners = smallMeet.divisions
      .flatMap((d) => standingsOf(smallMeet, d.name))
      .filter((r) => r.trc > 0)
      .map((r) => r.name);
    expect(trcWinners).toEqual(['Birdie']);
  });
});

// -------------------------------------------------------------- meet 2: A02

describe('example meet 2 (2026-A02)', () => {
  it('gives each sighthound breed its own division and pools the rest', () => {
    expect(largeMeet.divisions.filter((d) => d.type === 'breed').map((d) => d.name).sort()).toEqual([
      'AZAWAKH',
      'BORDER COLLIE',
      'SALUKI',
      'TAIGAN',
      'WHIPPET',
    ]);
    // The herding breeds run mixed: two Belgian Shepherds, and the only Dutch
    // Shepherd in the guide, who has nobody of her own to run against.
    const mixed = divisionNamed(largeMeet, 'MIXED');
    expect(mixed.type).toBe('mixed');
    expect(mixed.entryIds.map((id) => mapOf(largeMeet).get(id)!.breed).sort()).toEqual([
      'BELGIAN SHEPHERD DOG',
      'BELGIAN SHEPHERD DOG',
      'DUTCH SHEPHERD',
    ]);
  });

  it('splits a nine-dog division into races of 3, 2 and 4', () => {
    const whippets = divisionNamed(largeMeet, 'WHIPPET');
    const p1 = largeMeet.draws.find((d) => d.divisionId === whippets.id && d.program === 1)!;
    // 9 dogs is 3 / 2 / 4 in run order, not an even split (chart.ts).
    expect(p1.races.map((r) => r.slots.length)).toEqual([3, 2, 4]);
    expect(p1.races[2].isHP).toBe(true);
  });

  it('places a leftover with dogs it can fairly race and pays it mixed points only', () => {
    // A Sloughi entering alone has no division of his own (4.1.7). He is put
    // with the Azawakhs — comparable size and running style — not the Whippets.
    const sloughi = largeMeet.entries.find((e) => e.breed === 'SLOUGHI')!;
    expect(divisionNamed(largeMeet, 'AZAWAKH').leftoverIds).toContain(sloughi.id);
    expect(divisionNamed(largeMeet, 'WHIPPET').leftoverIds).toEqual([]);

    expect(row(largeMeet, 'AZAWAKH', sloughi.callName)).toEqual(
      expect.objectContaining({ place: 2, mrc: 0.5, brc: 0, nbrc: 0 })
    );
    // A leftover consumes no breed slot, so the Azawakh behind him still takes
    // the second breed award rather than the third.
    expect(row(largeMeet, 'AZAWAKH', 'Amidi')).toEqual(
      expect.objectContaining({ place: 3, brc: 0.5 })
    );
  });

  it('splits championship points between dogs tied on race points (5.2)', () => {
    // Bandit-S and Baker both finish on 15 in the 2nd and 3rd high-score slots
    // of an eligible entry of 9, so they share (1.5 + 0.5) / 2 = 1.0 each.
    expect(row(largeMeet, 'WHIPPET', 'Bandit-S')).toEqual(
      expect.objectContaining({ total: 15, brc: 1 })
    );
    expect(row(largeMeet, 'WHIPPET', 'Baker')).toEqual(
      expect.objectContaining({ total: 15, brc: 1 })
    );
    // And again a division over, on a smaller chart row: 0.5 each.
    expect(row(largeMeet, 'BORDER COLLIE', 'Critter')).toEqual(
      expect.objectContaining({ total: 12, brc: 0.5 })
    );
    expect(row(largeMeet, 'BORDER COLLIE', 'Akira')).toEqual(
      expect.objectContaining({ total: 12, brc: 0.5 })
    );
  });

  it('subtracts a champion who wins from the eligible entry (5.2)', () => {
    // Atari holds a BRC and wins the division outright. Placing above the first
    // non-titled dog he comes off the eligible entry: 6 starters, entry of 5.
    // He earns no breed points and still takes National Breed points, and
    // Dillon behind him is the High Score Dog for breed purposes.
    expect(dogNamed(largeMeet, 'Atari').hasBRC).toBe(true);
    expect(resultsOf(largeMeet, 'BORDER COLLIE').eligibleEntryBreed).toBe(5);
    expect(row(largeMeet, 'BORDER COLLIE', 'Atari')).toEqual(
      expect.objectContaining({ place: 1, brc: 0, nbrc: 2 })
    );
    expect(row(largeMeet, 'BORDER COLLIE', 'Dillon')).toEqual(
      expect.objectContaining({ place: 2, brc: 2 })
    );
  });

  it('gives Turtle Racing points only to a last dog that finished (5.7)', () => {
    const trcWinners = largeMeet.divisions
      .flatMap((d) => standingsOf(largeMeet, d.name))
      .filter((r) => r.trc > 0)
      .map((r) => r.name)
      .sort();
    expect(trcWinners).toEqual(['Ak-Tosh', 'Annie', 'Birdie']);

    // Dori finishes last in mixed but did not finish every race, which bars her.
    expect(standingsOf(largeMeet, 'MIXED').at(-1)!.name).toBe('Dori');
    expect(row(largeMeet, 'MIXED', 'Dori').trc).toBe(0);
  });
});
