// Builds src/data/sample-meet.json — the demo meet behind Home → "Load sample
// meet".
//
// Run with:  npm run build-sample
//
// The meet is generated by the real domain engine rather than written by hand,
// so the draws, rotations and points in it are the ones the app would actually
// produce. Hand-editing that JSON is how you get a demo that quietly disagrees
// with the rules it is demonstrating.
//
// Dogs are real entries from the bundled Grading Guide, picked by registration
// number below, so their names, owners and WAVEs match what a secretary sees
// when they search the guide. Owners are already published there.

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import guide from '../src/data/grading-guide.json';
import { drawFirstProgram, gradedSortKey } from '../src/domain/draw';
import { drawNextProgram } from '../src/domain/rotation';
import { gradeForWave } from '../src/domain/wave';
import { entryFromGuide } from '../src/store/meetStore';
import type {
  Division,
  Entry,
  GuideDog,
  MeetState,
  ProgramDraw,
  Race,
  RaceOutcome,
  Sex,
} from '../src/domain/types';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Deterministic RNG (mulberry32), so rebuilding gives the same meet. */
function seededRng(seed: number) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ---------------------------------------------------------------- the roster

interface Pick {
  reg: string;
  sex: Sex;
}

/**
 * Four divisions chosen to cover what a secretary actually meets, using the
 * breeds that actually turn out. By registrations with meet history the sport
 * is Whippets, Mixed Breeds, Lurchers and Windsprites, then Jack Russells,
 * Belgian Shepherds and Border Collies — the herding breeds are the popular
 * non-sighthound entry, not the Dutch Shepherd, of which the guide lists one.
 */
const ROSTER: { division: string; type: 'breed' | 'mixed'; dogs: Pick[]; leftovers?: Pick[] }[] = [
  {
    // Nine dogs is Figure 8.1's odd row: races of 3, 2 and 4 rather than an
    // even split, which is exactly the case worth having in a demo.
    division: 'WHIPPET',
    type: 'breed',
    dogs: [
      { reg: 'WH-251', sex: 'F' }, // Annex    22.0
      { reg: 'WH-288', sex: 'M' }, // Bandit-S 22.0
      { reg: 'WH-128', sex: 'M' }, // Baker    18.0
      { reg: 'WH-179', sex: 'F' }, // Babs     17.9
      { reg: 'WH-35', sex: 'F' }, //  Ailia    15.3, holds a BRC
      { reg: 'WH-235', sex: 'M' }, // Alias    15.0
      { reg: 'WH-51', sex: 'M' }, //  Axl      14.7
      { reg: 'WH-209', sex: 'F' }, // Baja     14.6
      { reg: 'WH-62', sex: 'F' }, //  Baba     13.8
    ],
  },
  {
    division: 'BORDER COLLIE',
    type: 'breed',
    dogs: [
      { reg: 'BC-10', sex: 'M' }, // Dillon  22.0
      { reg: 'BC-11', sex: 'M' }, // Atari   19.3, holds a BRC
      { reg: 'BC-38', sex: 'F' }, // Creek   16.8, holds a BRC
      { reg: 'BC-20', sex: 'F' }, // Critter 15.8
      { reg: 'BC-17', sex: 'F' }, // Chili   13.5
      { reg: 'BC-9', sex: 'M' }, //  Akira   11.7
    ],
  },
  {
    // The whole breed: the guide lists four Taigans and three entered.
    division: 'TAIGAN',
    type: 'breed',
    dogs: [
      { reg: 'TAIG-1', sex: 'M' }, // Azhidar 20.8, holds an MRC
      { reg: 'TAIG-2', sex: 'F' }, // Slinky  13.4
      { reg: 'TAIG-4', sex: 'M' }, // Ak-Tosh ungraded
    ],
  },
  {
    // The guide splits Salukis in two: four carry a Breed WAVE and eight carry
    // only a Mixed one. A breed division needs the first group.
    division: 'SALUKI',
    type: 'breed',
    dogs: [
      { reg: 'SA-23', sex: 'M' }, // Falcon 22.0
      { reg: 'SA-4', sex: 'M' }, //  Miraj  22.0
      { reg: 'SA-11', sex: 'F' }, // Annie  16.0
    ],
  },
  {
    // The reverse of the Salukis: eight Azawakh carry a Breed WAVE and not one
    // has a Mixed WAVE, which is what a breed that runs against its own looks
    // like in the guide.
    division: 'AZAWAKH',
    type: 'breed',
    dogs: [
      { reg: 'AZ-5', sex: 'M' }, // Anubi  22.0
      { reg: 'AZ-2', sex: 'F' }, // Amidi  16.0
      { reg: 'AZ-7', sex: 'F' }, // Birdie 14.0
    ],
    // The guide lists two Sloughis, so one entering alone has no division of
    // his own (4.1.7). Where a leftover is placed is the secretary's judgement
    // on size, speed and running style, and a Sloughi belongs with the Azawakhs
    // on all three — not with the Whippets, who are a different dog entirely.
    // He is judged on his Mixed WAVE here rather than his Breed WAVE, races the
    // whole field, and can take mixed points only.
    leftovers: [{ reg: 'SL-1', sex: 'M' }], // Asim al-Rhys, Sloughi, M 18.5
  },
  {
    // Where the non-sighthounds end up. Two Belgian Shepherds would be enough
    // for a breed division of their own under 4.1.5; keeping them with the lone
    // Dutch Shepherd instead is the secretary's call, which the app leaves open.
    division: 'MIXED',
    type: 'mixed',
    dogs: [
      { reg: 'BSD-10', sex: 'M' }, // Baloo  Belgian Shepherd M 22.0
      { reg: 'BSD-16', sex: 'F' }, // Cassie Belgian Shepherd M 14.8
      { reg: 'DS-2', sex: 'F' }, //   Dori   Dutch Shepherd   M  9.9 — the only
      //                                  one in the guide, so mixed is her meet
    ],
  },
];

/** Entered and then pulled before the draw — shown struck through in Entries. */
const PRE_SCRATCHED: Pick[] = [{ reg: 'WH-144', sex: 'F' }]; // Ace

/**
 * The things that go wrong at a meet, scripted so the demo always shows them.
 * A DQ or a scratch takes the dog out of every later program (6.1.4 / 4.1.3),
 * which is itself worth seeing.
 */
// The two that end a dog's meet are put in the two largest divisions, so the
// small breed divisions are not left racing pairs in program 3.
const INCIDENTS: Record<string, Record<number, RaceOutcome['kind']>> = {
  'WH-209': { 1: 'OC' }, //  Baja runs off course in program 1 and carries on
  'WH-235': { 2: 'DQ' }, //  Alias is disqualified in program 2 and is done
  'BC-17': { 2: 'ABS' }, //  Chili is scratched before program 2 and is done
  'DS-2': { 3: 'DNF' }, //   Dori fails to finish, which also bars her from the
  //                         Turtle Racing points her placing would have earned
};

// ------------------------------------------------------------------ building

const byReg = new Map<string, GuideDog>(guide.dogs.map((d) => [d.regNo, d as GuideDog]));
const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

function makeEntry({ reg, sex }: Pick, preScratched = false): Entry {
  const dog = byReg.get(reg);
  if (!dog) throw new Error(`${reg} is not in the bundled Grading Guide`);
  const entry = entryFromGuide(dog);
  return {
    ...entry,
    // Readable and stable, so rebuilding this file does not churn every id.
    id: `entry-${slug(reg)}`,
    sex,
    preScratched,
    // A dog with no WAVE on the side it is running gets a grade from the
    // secretary. Its Breed WAVE is the honest basis for that guess.
    fteGrade: gradeForWave(dog.bwave ?? dog.mwave ?? 0),
  };
}

const entries: Entry[] = [
  ...ROSTER.flatMap((d) => [...d.dogs, ...(d.leftovers ?? [])].map((p) => makeEntry(p))),
  ...PRE_SCRATCHED.map((p) => makeEntry(p, true)),
];
const entryMap = new Map(entries.map((e) => [e.id, e]));

const divisions: Division[] = ROSTER.map((d) => ({
  id: `div-${slug(d.division)}`,
  type: d.type,
  name: d.division,
  entryIds: [...d.dogs, ...(d.leftovers ?? [])].map((p) => `entry-${slug(p.reg)}`),
  leftoverIds: (d.leftovers ?? []).map((p) => `entry-${slug(p.reg)}`),
  ungraded: false,
}));

// Fixed so the demo is the same meet every time it is rebuilt. Override with
// SAMPLE_SEED to reroll it — the results are meant to be a plausible meet, and
// which plausible meet is a choice, so it is worth being able to look at a few.
const SEED = Number(process.env.SAMPLE_SEED ?? 7);
const rng = seededRng(SEED);

/** Finish a race: fastest first by form, with any scripted incident applied. */
function runRace(race: Race, division: Division): void {
  const outcomes: Record<string, RaceOutcome> = {};
  const runners: { id: string; form: number }[] = [];

  for (const slot of race.slots) {
    const entry = entryMap.get(slot.entryId)!;
    const incident = INCIDENTS[entry.regNo ?? '']?.[race.program];
    if (incident) {
      outcomes[slot.entryId] = { kind: incident } as RaceOutcome;
      continue;
    }
    // Better-graded dogs usually win, and sometimes do not.
    runners.push({ id: slot.entryId, form: gradedSortKey(entry, division) + (rng() - 0.5) * 9 });
  }

  runners.sort((a, b) => b.form - a.form);
  // Places run 1..n across the dogs that finished; a dog that did not is
  // simply absent from the numbering (validatePlaces enforces this).
  runners.forEach((r, i) => {
    outcomes[r.id] = { kind: 'placed', place: i + 1 };
  });

  race.outcomes = outcomes;
  race.finished = true;
}

/** Stable, readable race ids in place of the timestamped ones newId hands out. */
function withStableIds(draw: ProgramDraw): ProgramDraw {
  return {
    ...draw,
    races: draw.races.map((r) => ({ ...r, id: `race-p${draw.program}-${slug(draw.divisionId)}-${r.raceNo}` })),
    locked: true,
  };
}

const draws: ProgramDraw[] = [];
for (const program of [1, 2, 3] as const) {
  for (const division of divisions) {
    const draw =
      program === 1
        ? drawFirstProgram(division, entryMap, rng)
        : drawNextProgram(division, draws, entryMap, program, rng);
    const finished = withStableIds(draw);
    for (const race of finished.races) runRace(race, division);
    draws.push(finished);
  }
}

const meet: MeetState = {
  info: {
    clubName: 'High Desert Racing Club',
    meetId: '2026-A02',
    date: '2026-08-15',
    fteThreshold: 0.75,
  },
  // Always opens on Home so the demo shows what was loaded before anything else.
  phase: 'home',
  entries,
  divisions,
  draws,
  overrides: {},
};

// Only meet 2 is generated. sample-meet-1.json is an older capture from the
// real UI, kept as it is because it is a different shape of meet — a smaller
// entry, 19 dogs in 4 divisions — and regenerating it would only turn it into
// another version of this one.
const target = join(root, 'src', 'data', 'sample-meet-2.json');
writeFileSync(target, `${JSON.stringify(meet, null, 2)}\n`);

const races = draws.reduce((n, d) => n + d.races.length, 0);
console.log(
  `Wrote ${entries.length} entries (${entries.filter((e) => e.preScratched).length} pre-scratched), ` +
    `${divisions.length} divisions, ${races} races across 3 programs.`
);
